### ISSUE TITLE
[Feature Request] Ts3 driver, not show server password when no password is set

### ISSUE THREAD

**Issue by Meganitrospeed** [warlof/seat-connector#10]
Not sure why nobody reads it, But When no server password it set it still displays it as an empty box and everybody ask`s ¿ What is the server password ?
Just would nice to have it not shown when not set

**Comment by warlof** [comment]
Hi @Meganitrospeed 

Are you talking about the password field on the registration box ?

**Comment by Meganitrospeed** [comment]
o/) @warlof 
Yes, Im speaking about the password field ,it never fails, everytime somebody gets set-up in SeAT he asks about it

**Comment by sgeine** [comment]
I actually have this issue as well and it's broken teamspeak completely. No one can get beyond it.
<img width="984" alt="Screen Shot 2019-08-21 at 3 21 05 PM" src="https://user-images.githubusercontent.com/48392830/63472576-765bb100-c427-11e9-9948-7e8193626f81.png">

There's a secondary issue in that the box only shows up for me, the administrator. the tab shows up for everyone but the teamspeak box isn't there. I'm not clear how to resolve the "unregistered" issue as well. Perhaps this is a byproduct of not being able to pass the password field

<img width="521" alt="Screen Shot 2019-08-21 at 3 21 20 PM" src="https://user-images.githubusercontent.com/48392830/63472581-7a87ce80-c427-11e9-959e-443187a34e66.png">

**Comment by sgeine** [comment]
@Meganitrospeed are you able to bypass this somehow without a password set?

**Comment by Meganitrospeed** [comment]
> @Meganitrospeed are you able to bypass this somehow without a password set?

You dont need a password, thats why I was requesting to get it removed when no password is used

**Comment by sgeine** [comment]
@Meganitrospeed I got that your server doesn't need a password, I don't have one on mine either. Only seat permissions. What I was asking was how you were able to get past the password dialogue. What button do you click?

**Comment by Meganitrospeed** [comment]
@sgeine The green button that says Confirm
