### ISSUE TITLE
[Issue] Cant change Identity once linked

### ISSUE THREAD

**Issue by Meganitrospeed** [warlof/seat-connector#14]
So, once you link an Identity to the Ts3 connector ( haven't tried other drivers ) and you re-do Link 
( You linked once, go again and click confirm again ) It does not get your new Unique ID
https://i.imgur.com/xFtHPtB.png

Also, this happened to that particular user while signing up

Have tried it with multiple identities a quick fix would probably be to bring back the "Remove User mapping" button

Haven't found a way to fix it, except to use an Alt to get roles which isn't a "fix" but a good workaround

**Comment by Meganitrospeed** [comment]
Just to add, it looks like it has nothing to do with the Timeout, happens with everybody

**Comment by warlof** [comment]
@Meganitrospeed did you put SeAT address on your teamspeak query whitelist?

**Comment by warlof** [comment]
@Meganitrospeed how is it going since last week release?

**Comment by Meganitrospeed** [comment]
Havent had a chance to test it yet @warlof but I would love if deleting Linked accounts could be introduced again, I usually resolve this stuff deleting the entire user and recreating him

**Comment by warlof** [comment]
Close due to inactivity
