### ISSUE TITLE
Registration: 	ErrorID: 1541 | Message: invalid parameter size

### ISSUE THREAD

**Issue by kaho88** [warlof/seat-connector#19]
Hey,

installed your connector and it did a great job for Discord.
Now i'm running into Problems with Teamspeak.

I made a Querry Login and added it Successfully.
Now when i push on "Join Server" i get this Window:
![Download](https://user-images.githubusercontent.com/24758285/66195524-15b2cb80-e697-11e9-8d3f-c66e40e13eda.png)

If i change my Nickname and push COnfirm i get this Error:

ErrorID: 1541 | Message: invalid parameter size

What i'm doing wrong?

Greetings

**Comment by warlof** [comment]
You're not following the wizard instructions. You must sign in with provided information.
However, the displayed nickname should not be editable. 

What's your browser?

**Comment by kaho88** [comment]
To be fair i didnt had a wizzard....
Updated from an old Discord git and there was only the Discord and Teamspeak Connector.
No Wizard or Something :-/

On the Settings side i only can add the query and IPs and save it.

I'm using Chrome :-)

**Comment by warlof** [comment]
you put it in your initial message, so I assume you had it :P

**Comment by kaho88** [comment]
oh well sorry haha... i updated the old version to the new.
Should i deinstall the whole pack and reinstall?

**Comment by warlof** [comment]
no need, you have a conversion script available in the package if you were coming from a version prior to 4.x.

`seat-connector:convert:teamspeak` for teamspeak
`seat-connector:convert:discord` for discord

**Comment by warlof** [comment]
Close due to inactivity
