### ISSUE TITLE
[Bug?] SeAT actuating as the user who created the Querry Login

### ISSUE THREAD

**Issue by Meganitrospeed** [warlof/seat-connector#20]
On the previus version the Bot Name on Ts3 was always the name you gave him or a random generated string ( I think ) like SeAT-4343241

Right now SeAT is actuating as the user who created the Server Querry login
For example I created the Server querry login

So when something get updates you see Meganitrospeed added roles XXX

Instead of SeAT, makes some hilarious reactions when people start screaming at me xD

Will be looking this night at the code to see if I can switch something myself and make a pull request

**Comment by warlof** [comment]
that's what happening when you create a query login from the client using `tools > server query login`.
the created user is made for your own usage with your own permissions.

That's the reason why I used to redirect user to the `serveradmin` query user created at server start.

Alternatively, you need to create a specific identities for that bot - so your status will not affect the bot.

Connect to the server with the new identity and grant the new user a role getting enough permissions.
