### ISSUE TITLE
Rate limit errors

### ISSUE THREAD

**Issue by Boot103** [warlof/seat-connector#25]
Hi, When I click reset everybody I get loads of rate limit errors and peoples roles do not seem to be updating. 

https://i.imgur.com/V2oI2L8.png

**Comment by jediefe** [comment]
That seems to be normal if a lot of requests are sent at once. I experienced this problem when all Discord names were updated at once when setting up the plugin. I think this needs to be resolved by implementing a rate limiter for the respective job. For now this can also be solved by waiting for multiple job cycles until everything has been processed. Depending on the number of registered users this might take a while.

**Comment by warlof** [comment]
Such a weird thing.

Technically, throttler exists and is apply over each sent request behind the Discord driver.
https://github.com/warlof/seat-discord-connector/blob/master/src/Caches/RedisRateLimitProvider.php

called here
https://github.com/warlof/seat-discord-connector/blob/6ff27d2d920ea42e0f47940ebb7dd4175c5846db/src/Driver/DiscordClient.php#L252
