### ISSUE TITLE
Discord Connector does not know if the callback url should be https or http

### ISSUE THREAD

**Issue by AlienXAXS** [warlof/seat-connector#29]
Hi Warlof,
I for awhile was scratching my head as to why I and other people were getting OAuth errors on discord saying that the callback URL did not match.

After looking at the callback URL closely, I noticed that the connector will take whatever method you're using to connect to the site as truth.

For example, if I have in my discord bot the following oauth url:
![image](https://user-images.githubusercontent.com/1773445/72464057-84421200-37cc-11ea-9b88-b579dc8334a3.png)

It works fine if i were previously on https://haratseat.agngaming.com, however the callback URL fails if you were to goto the SeAT website via a non SSL connection, instead the callback URL would not contain the https, only http.

Not too sure how to solve this, if even possible - but i feel the Discord Connector should fix this instead of the fix being "Add a redirect rule to only allow HTTPS" for example.

** Edit **
I also want to add that my .env URL has https on it too, perhaps you can take it from here as truth?
![image](https://user-images.githubusercontent.com/1773445/72464427-24983680-37cd-11ea-860a-e83b3dd93857.png)

**Comment by warlof** [comment]
Hi @AlienXAXS 

The exactly same apply to SeAT - it's not up to the source to guess the remote.
Enforce https in your config and you'll be good.

User =[http]=> your http service ~[redirect to https]~ your http service =[https]=> SeAT

**Comment by AlienXAXS** [comment]
Hi bud,
Other applications that require the admin to input a URL (such as APP_URL) consider this the single point of truth, can this not be used as a redirect within SeAT itself?

Like, if your source != APP_URL, then header("Location: " . $Settings->APP_URL) for example?

**Comment by ppfeufer** [comment]
How about you force SSL for your website in your webserver vhost configuration?

Incoming HTTP > Redirect to HTTPS

That way the website user is always on HTTPS before he actually sees anything.

**Comment by warlof** [comment]
Closing the issue since it's server configuration related. If you're using https,enforce it by redirecting all http input to https.

As said, the exactly same apply to core itself.
