### ISSUE TITLE
Newest Version on Composer Requires Seat 4.0.0

### ISSUE THREAD

**Issue by kanelarrete** [warlof/seat-connector#31]
Hello. 

I run seat in docker and currently running into an issue where it will not start seat-app due to dependencies on this package. It is requiring 4.0.0 where as this has not been released yet. Any suggestions on how to fix this?

Thanks.

**Comment by warlof** [comment]
For an unknown reason, composer attempt to pull a version when it can't pass active dependencies.
You'll have to stick connector and drivers versions in your `.env` file to resolve that.

To do so, append the version just after package, separated by a semi-colon : `vendor/package:version`

Last stable versions compatible with SeAT 3.0.x are listed bellow :

| Vendor | Package | Version | ENV string |
| ------ | ------------------------ | ----- | ------------------------------------- |
| warlof | seat-connector              | 1.4.4 | `warlof/seat-connector:1.4.4`             |
| warlof | seat-discord-connector | 4.0.4 | `warlof/seat-discord-connector:4.0.4` |
| warlof | seat-teamspeak            | 4.1.2 | `warlof/seat-teamspeak:4.1.2`            |

For non docker installation, the same rule apply, except you have to make change directly into `composer.json` instead `.env` file.

**Comment by kanelarrete** [comment]
Perfect. That worked great. Thanks for the quick response.
