### ISSUE TITLE
" Identities" ERROR 500 and "'refresh_tokens'" Error

### ISSUE THREAD

**Issue by kaho88** [warlof/seat-connector#35]
Hey,

we updated to the new Connecter, Discord-Connector & Teamspeak Connector.

If you try to point the "Identities" side you get a "Error 500" Message.
So you arnt able to Connect to Discord & Teamspeak.

The Old System gave us a schedule to convert the Userprofiles.

If i check the Logs i get:
`Unable to update the user blablabla. Trying to get property 'refresh_tokens' of non-object`

Opening the User Table we get:
`DataTables warning: table id=dataTableBuilder - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

![Screenshot_7](https://user-images.githubusercontent.com/24758285/90918578-2e2df080-e3e5-11ea-8750-65f1657e6a0f.png)

Thank you :-)

**Comment by warlof** [comment]
hey @kaho88 

did you run migrations ?

**Comment by kaho88** [comment]
Hey warlof,

sorry... i guess you cant read my name anymore today xD

yes we used `docker-compose exec seat-web php artisan migrate`

**Comment by warlof** [comment]
Why should I ? no reason.

Can you post your laravel log just after beeing into `Connector > User Mapping` ?
Also, does `Connector > Identities` work ?

**Comment by kaho88** [comment]
Connector > Identities didnt work... But:

 i think that has nothing to do with your Connector.
We disabled all Plugins and it worked only with the Connector.

It seems the "SRP Plugin" is giving a Database error that cause a problem with the Connector....

So i guess nothing bad on your site here....

**Comment by warlof** [comment]
Logs still à thing. So will now what we're looking for 😉

**Comment by kaho88** [comment]
Hm... I rly dont get wich Logs you need :-(
If i search for Tags i only get : 

DriverApplyPolicies
DriverUpdateSets

**Comment by warlof** [comment]
https://eveseat.github.io/docs/troubleshooting/#live-logs-docker-installs

**Comment by kaho88** [comment]
didnt forget you warlof. Give me another day to sort the logs - weekend is always abit stressful

**Comment by kaho88** [comment]
Sorry warlof... As now it is working fine with the connector i cant get the logs for you.
But trying to Install the SRP Plugin dont work anymore due a error in the installation.

So cant simulate it for now...
Will Re-Open when the SRP Plugin will give errors on your Connector.
