### ISSUE TITLE
Error when trying to connect character to discord

### ISSUE THREAD

**Issue by bradleyshelley** [warlof/seat-connector#36]
Warlof\Seat\Connector\Exceptions\DriverSettingsException
Parameter guild_id is missing.
![image](https://user-images.githubusercontent.com/66140401/91115760-8caad700-e650-11ea-9ca0-c64011cc4212.png)

**Comment by warlof** [comment]
Hey

Is it a new setup? 
Did you check both "public bot" and "require oauth2 grant" option on the bot section from your discord app?

**Comment by bradleyshelley** [comment]
Yes new setup.
I have checked both.

**Comment by bradleyshelley** [comment]
any update?

**Comment by warlof** [comment]
Is your bot setup like this?

![Screenshot_20200901-084032](https://user-images.githubusercontent.com/648753/91810857-e9008e80-ec2e-11ea-8ee1-59c25dd8116e.png)

If it's not the case, please adapt. 

In all case, try to setup the connector again as it seems required data didn't be provided.

**Comment by bradleyshelley** [comment]
![image](https://user-images.githubusercontent.com/66140401/91811829-bdad7d80-ebf5-11ea-815e-26d6f78841b8.png)
This is configured and still receiving the 500 error

**Comment by warlof** [comment]
Can you renew your secret, ensure both public bot and requires oauth2 code grant are checked and redo the discord setup ?
There might be some cache on Discord backend, but for sure, if we don't received `guild_id` - it it related to `public bot` beeing unchecked.

![image](https://user-images.githubusercontent.com/648753/92128593-d8a10d00-ee02-11ea-977c-405fcf4f2f15.png)

**Comment by bradleyshelley** [comment]
Now I am getting this error.
![image](https://user-images.githubusercontent.com/66140401/92315603-7fc1a800-efad-11ea-87f4-50e2cedefe8c.png)

**Comment by warlof** [comment]
That's caused by a requested role to be grant by the bot which is greater than the bot role itself.
Please review your discord role sorting.
