### ISSUE TITLE
Error when attemping to remove a user mapping for a user that has manually disconnected from server.

### ISSUE THREAD

**Issue by beelitzs** [warlof/seat-connector#37]
![error](https://user-images.githubusercontent.com/4109815/92257398-83571f80-ef18-11ea-9cdf-823ff0130c12.png)

Error shows as linked, however user still remains in table with no obvious way to remove it.
Only way at the moment might be to manually remove from the DB?

**Comment by warlof** [comment]
Hi,

Which seat-discord-connector version are you using ?

**Comment by beelitzs** [comment]
Seems like I'm using an older version. v 1.4.5
I thought that seat was supposed to auto update packages.
![Screenshot_4](https://user-images.githubusercontent.com/4109815/92267824-a7206280-ef24-11ea-9a78-216e3ec58112.png)
I'll attempt to force an update and see if it fixes the issue.

**Comment by beelitzs** [comment]
@warlof When trying to update seat-connector its being blocked by seat-discord-connector, but I have the same issue in reverse when I try to update seat-discord-connector.

Any ideas?
![Screenshot_5](https://user-images.githubusercontent.com/4109815/92270554-9cb49780-ef29-11ea-9ad4-a505c30d3fdc.png)
![Screenshot_6](https://user-images.githubusercontent.com/4109815/92270564-a1794b80-ef29-11ea-97ae-7fc222dbed08.png)

**Comment by warlof** [comment]
Yes, 1.4.5 is last version for SeAT 3.x

I'll double check, but I think it's a case which has been handled on last version only.

**Comment by beelitzs** [comment]
No problem, thanks for that.
I've worked around the issue by removing the database entry manually anyways.

**Comment by warlof** [comment]
Yes, confirmed - it's a case which should non longer happening with new version.

https://github.com/warlof/seat-connector/blob/afcc901edeeeafbe9fa90b36e28a6e4fc5e22791/src/Http/Controllers/UsersController.php#L93-L94
