### ISSUE TITLE
[Feature Request] More granular roles

### ISSUE THREAD

**Issue by Nfinished** [warlof/seat-connector#38]
Hi! Right now access management is exposed as a role only through full admin, it'd be nice if that could be broken up per driver, or at least a role that _only_ allows access management modifications and not settings. Thank you for all the work that you do!

**Comment by warlof** [comment]
Hi,

Since seat-connector 1.0.0, a permission called `Security` which restrict access to both `Access Manager` and `User Mapping` has been added.
