### ISSUE TITLE
seat-teamspeak: No value works for API Base URI

### ISSUE THREAD

**Issue by holliava** [warlof/seat-connector#39]
The SEAT Teamspeak Connector cannot be configured when newly installed as the settings requested in Connector/Settings are nonsense.

![Screenshot_2020-09-13_20-54-19](https://user-images.githubusercontent.com/71203779/93016275-57682800-f603-11ea-9653-8ce151e5cf41.png)

The correct base uri for a serverquery connection should be **telnet://host:port/** but when I enter this libcurl complains that it can't understand that protocol. When I enter a HTTP URI the server then connects to that URI and attempts to send serverquery commands via HTTP, but ts3server does not have a HTTP interface.

Am I missing something here?

Version 4.1 of the connector used ts3Admin to connect to ts3server query port via fsockopen.

Version 5.0 of the connector uses GuzzleFetcher to connect to ts3server using HTTP, expecting a JSON response. The TeamSpeak 3 server doesn't speak either HTTP or JSON. Help?

**Comment by warlof** [comment]
SeAT connector compatible with v4 is using a driver which consume new http "rest" api instead of the old server query system.

Default base Uri is `http://server:10080`.

> CAUTION
> 
> With version 5, this driver switched from old server query system to new API backend. You'll have to update settings and fill base URI and API Key. If using docker container, you can enable the new API backend by adding http to the TS3SERVER_QUERY_PROTOCOLS environment variable. An API KEY is generated at first start, however, if you need to generate one, you can do this by following this topic https://community.teamspeak.com/t/what-is-apikey-for/6156/2

**Comment by holliava** [comment]
Thank you!

I had not noticed that ts3server had added a HTTP query port, I've enabled this and everything is working.

I really appreciate your work on this connector by the way, so helpful.

Have a good one!

--holli
