### ISSUE TITLE
Add an 'Update roles now' button on web interface

### ISSUE THREAD

**Issue by matsfinsas** [warlof/seat-connector#4]
After update `warlof/seat-teamspeak` 4.x the web interface button to update Sets/Server groups are missing.

It works as normal using `php artisan seat-connector:apply:policies`.

**Comment by warlof** [comment]
@Xtrah indead, commands are non longer usable from frontend
However - they are both schedulable :
 - `seat-connector:sync:sets` will update "sets" from all installed driver. Sets is the universal name for Teamspeak Server Group, Slack Channel, Discord Role, etc...
 - `seat-connector:apply:policies` will apply your defined policy rules to all registered users

**Comment by Xtrah** [comment]
It would also be preferable if it automatically checks and adds the correct role immediately when a new Identity is checked/added to a user. Right now a user would have to wait until the next `seat-connector:sync:sets` is scheduled after the Identity is added.
