### ISSUE TITLE
Updating sets on Discord driver unsuccessful

### ISSUE THREAD

**Issue by LuciousLisa** [warlof/seat-connector#43]
**SeAT** v4
**SeAT Connector** v2.0.2
**Discord Connector** v5.0.0

**Expected result:** being able to choose Discord roles so that they can be assigned.
**Current result:** no Discord roles available to assign to SeAT roles, corp titles, etc.

**Steps to reproduce:**
- On Discord: drag bot role to top of roles list in server settings
- On SeAT: navigate to `Connector > Settings`
- Select `Discord` in drivers dropdown, click `Update Sets` button
- Keep an eye on Horizon jobs to see the job `DriverUpdateSets` running (orange pause icon)
- After several minutes, see Horizon job get red cross icon, indicating failure (note that the job does not show under `Failed Jobs` in Horizon)
- Navigate to `Connector > Access Management`
- Select type: `Role Filters`, select role: `Full members`
- Type in Set field `Mem` (from Members role available on Discord)
- Result: No results found

Please let me know if I'm doing something wrong or if there's something else I could be doing to resolve this issue. If not, then please consider this a bug report. If more info is needed I'll be happy to provide logs, screenshots etc.

**Comment by warlof** [comment]
> After several minutes, see Horizon job get red cross icon, indicating failure (note that the job does not show under Failed Jobs in Horizon)

What's the reason of the failure? You should get it by going in the job. In all case, if the job is failing, you can't get anything in SeAT.

**Comment by LuciousLisa** [comment]
Where should I be able to find a reason for the failure? I'll add the following screenshots to illustrate what I'm seeing in Horizon.

- Job running: https://i.imgur.com/sLQxV9x.png
- Clicking `View detail` during the job results in this page: https://i.imgur.com/ewDxl48.png
- Job failed: https://i.imgur.com/4fdUYjj.png
- Clicking the (now clickable) `DriverUpdateSets` text results in in this page, which won't load. Note that other failed jobs can be clicked to view more details, such as a stack trace: https://i.imgur.com/ATIYrWG.png
- It doesn't show up in the list of failed jobs: https://i.imgur.com/HQsogSg.png

I understand that failed jobs result in a lack of data. Please advice on how to proceed to resolve this issue.

**Comment by AstralDestiny** [comment]
GuzzleHttp\Exception\ClientException: Client error: `GET https://discord.com/api/guilds/734916090597212221/roles` resulted in a `401 Unauthorized` response:
--
{"message": "401: Unauthorized", "code": 0}
in /var/www/seat/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

I pretty much get this, Don't know what I'm doing wrong if anything?
Same steps as the above but confused on the 401 Unauthorized response when I try and pull roles.

**Comment by AstralDestiny** [comment]
Warlof\Seat\Connector\Jobs\DriverUpdateSets
Stack Trace from Horizon https://pastebin.com/KXsGThnD
And
Warlof\Seat\Connector\Jobs\DriverApplyPolicies
Stack Trace from Horizon https://pastebin.com/r9MRx3yj

DATA:
`{
client: null,
driver: "discord",
tags: [
"connector",
"discord"
],
job: null,
connection: null,
queue: "high",
chainConnection: null,
chainQueue: null,
delay: null,
middleware: [
],
chained: [
]
}
`

**Comment by kevinouw** [comment]
getting the same issue : 
Warlof\Seat\Connector\Jobs\DriverApplyPolicies
ID
1073113
Queue
high
Tags
connector, discord
Failed At
20-10-18 19:35:19
Error
GuzzleHttp\Exception\ClientException: Client error: `GET https://discord.com/api/guilds/158345365421162497/members?limit=1000` resulted in a `403 Forbidden` response:
{"message": "Missing Access", "code": 50001}
in /var/www/seat/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /var/www/seat/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /var/www/seat/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/seat/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/seat/vendor/warlof/seat-discord-connector/src/Driver/DiscordClient.php(264): GuzzleHttp\Client->request('GET', 'guilds/15834536...', Array)
#11 /var/www/seat/vendor/warlof/seat-discord-connector/src/Driver/DiscordClient.php(298): Warlof\Seat\Connector\Drivers\Discord\Driver\DiscordClient->sendCall('GET', '/guilds/{guild....', Array)
#12 /var/www/seat/vendor/warlof/seat-discord-connector/src/Driver/DiscordClient.php(135): Warlof\Seat\Connector\Drivers\Discord\Driver\DiscordClient->seedMembers()
#13 /var/www/seat/vendor/warlof/seat-connector/src/Jobs/DriverApplyPolicies.php(107): Warlof\Seat\Connector\Drivers\Discord\Driver\DiscordClient->getUsers()
#14 [internal function]: Warlof\Seat\Connector\Jobs\DriverApplyPolicies->handle()
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Warlof\Seat\Connector\Jobs\DriverApplyPolicies))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Warlof\Seat\Connector\Jobs\DriverApplyPolicies))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Warlof\Seat\Connector\Jobs\DriverApplyPolicies), false)
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'high', Object(Illuminate\Queue\WorkerOptions))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high')
#30 /var/www/seat/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#31 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#37 /var/www/seat/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#39 /var/www/seat/vendor/symfony/console/Application.php(992): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/seat/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 {main}
Data
{
  "client": null,
  "driver": "discord",
  "terminator": false,
  "tags": [
    "connector",
    "discord"
  ],
  "job": null,
  "connection": null,
  "queue": "high",
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": []
}

**Comment by AstralDestiny** [comment]
Ah nvm Got it all working :)

**Comment by LuciousLisa** [comment]
> Ah nvm Got it all working :)

Would you mind telling us how? I have yet to receive a reply from the dev and would love to solve this as well. Please provide the steps you took to resolve the problem.

**Comment by AstralDestiny** [comment]
I thought I needed
warlof/seat-discord-connector and warlof/seat-connector for the discord driver to function but no just needed the First :)

**Comment by AstralDestiny** [comment]
> > Ah nvm Got it all working :)
> 
> Would you mind telling us how? I have yet to receive a reply from the dev and would love to solve this as well. Please provide the steps you took to resolve the problem.

I thought I needed
warlof/seat-discord-connector and warlof/seat-connector for the discord driver to function but no just needed the First :)

**Comment by kevinouw** [comment]
@AstralDestiny https://eve-seat.slack.com/archives/CAPC5V8QK/p1602192886111900

**Comment by LuciousLisa** [comment]
Note that neither of these solutions (remove connector & reassign bot) have resulted in a fix for this issue.

**Comment by warlof** [comment]
Hi,

what about this check on the bot app ?
seems a new thing, according to some user, it seems to fix the sync.

![image](https://user-images.githubusercontent.com/648753/98730216-3ff7b200-239c-11eb-9aca-c044efab40bd.png)
