### ISSUE TITLE
Discord does not sync users anymore

### ISSUE THREAD

**Issue by kevinouw** [warlof/seat-connector#44]
Seat information:
Plugins
Core
 SeAT Module Versions
 SeAT API
Installed: v3.0.8
Current: 
Url: https://github.com/eveseat/api
 SeAT Console
Installed: v3.0.6
Current: 
Url: https://github.com/eveseat/console
 SeAT Eve API
Installed: v3.0.22
Current: 
Url: https://github.com/eveseat/eveapi
 SeAT Notifications
Installed: v3.0.6
Current: 
Url: https://github.com/eveseat/notifications
 SeAT Services
Installed: v3.0.11
Current: 
Url: https://github.com/eveseat/services
 SeAT Web 
Installed: v3.0.28
Current: 
Url: https://github.com/eveseat/web

Logs:
Warlof\Seat\Connector\Jobs\DriverApplyPolicies
ID
1073113
Queue
high
Tags
connector, discord
Failed At
20-10-18 19:35:19
Error
GuzzleHttp\Exception\ClientException: Client error: `GET https://discord.com/api/guilds/158345365421162497/members?limit=1000` resulted in a `403 Forbidden` response:
{"message": "Missing Access", "code": 50001}
in /var/www/seat/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /var/www/seat/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /var/www/seat/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/seat/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/seat/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/seat/vendor/warlof/seat-discord-connector/src/Driver/DiscordClient.php(264): GuzzleHttp\Client->request('GET', 'guilds/15834536...', Array)
#11 /var/www/seat/vendor/warlof/seat-discord-connector/src/Driver/DiscordClient.php(298): Warlof\Seat\Connector\Drivers\Discord\Driver\DiscordClient->sendCall('GET', '/guilds/{guild....', Array)
#12 /var/www/seat/vendor/warlof/seat-discord-connector/src/Driver/DiscordClient.php(135): Warlof\Seat\Connector\Drivers\Discord\Driver\DiscordClient->seedMembers()
#13 /var/www/seat/vendor/warlof/seat-connector/src/Jobs/DriverApplyPolicies.php(107): Warlof\Seat\Connector\Drivers\Discord\Driver\DiscordClient->getUsers()
#14 [internal function]: Warlof\Seat\Connector\Jobs\DriverApplyPolicies->handle()
#15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Warlof\Seat\Connector\Jobs\DriverApplyPolicies))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Warlof\Seat\Connector\Jobs\DriverApplyPolicies))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(Warlof\Seat\Connector\Jobs\DriverApplyPolicies), false)
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\Queue\Jobs\Job->fire()
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'high', Object(Illuminate\Queue\WorkerOptions))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'high')
#30 /var/www/seat/vendor/laravel/horizon/src/Console/WorkCommand.php(46): Illuminate\Queue\Console\WorkCommand->handle()
#31 [internal function]: Laravel\Horizon\Console\WorkCommand->handle()
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#37 /var/www/seat/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#39 /var/www/seat/vendor/symfony/console/Application.php(992): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#40 /var/www/seat/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /var/www/seat/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/seat/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 {main}
Data
{
  "client": null,
  "driver": "discord",
  "terminator": false,
  "tags": [
    "connector",
    "discord"
  ],
  "job": null,
  "connection": null,
  "queue": "high",
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": []
}

This has worked before but no longer since 07-10-2020
Bot is still there still has access which it should.

**Comment by rdymade** [comment]
same issue for me:
![image](https://user-images.githubusercontent.com/6643263/96443566-1cae6c80-120d-11eb-912e-bc326e2894b9.png)

**Comment by rdymade** [comment]
@kevinouw 
found a working solution on slack
![image](https://user-images.githubusercontent.com/6643263/96444485-a27ee780-120e-11eb-83f6-7b0f9460057e.png)

its working for me now again.

**Comment by excme** [comment]
> @kevinouw
> found a working solution on slack
> ![image](https://user-images.githubusercontent.com/6643263/96444485-a27ee780-120e-11eb-83f6-7b0f9460057e.png)
> 
> its working for me now again.

Is it right?
![image](https://user-images.githubusercontent.com/13168074/97039270-d2aee900-1574-11eb-8817-86432a9cd9d0.png)

**Comment by bpallares** [comment]
> @kevinouw
> found a working solution on slack
> ![image](https://user-images.githubusercontent.com/6643263/96444485-a27ee780-120e-11eb-83f6-7b0f9460057e.png)
> 
> its working for me now again.

This worked for me and should be linked to `Known issues` https://github.com/warlof/seat-discord-connector

**Comment by kevinouw** [comment]
can be closed warlof contacted me with the slack fix
