### ISSUE TITLE
Bug? Feature Request? Teamspeak provisioning extra roles

### ISSUE THREAD

**Issue by Nfinished** [warlof/seat-connector#46]
The Discord connector only applies alliance and corporation linked roles based on the main character in seat, but the Teamspeak connector appears to apply roles based on _all_ linked characters under the account. It feels like they should both work like Discord.

**Comment by warlof** [comment]
Hi,

The same logic is applied accross each driver.
Are you sure your policy is the same between discord and teamspeak?

**Comment by Nfinished** [comment]
My mistake, looks like another admin hadn't evenly applied policies. Thanks!
