### ISSUE TITLE
SEAT Mumble Connector

### ISSUE THREAD

**Issue by elrond1975** [warlof/seat-connector#48]
Hi! Maybe not quite the right place for this post, but ... You had a module to work with Mamble (2019). Is it possible to use / migrate in the new version 4.0?

https://github.com/wfjsw/seat-mumble-connector#readme
warlof/seat-mumble-connector

**Comment by warlof** [comment]
Hi,

I never edited any mumble connector. I don't understand anything about it :')
This one is provided by @wfjsw - as far as I remember, it has been provided as it - but you'll find a better support on the linked repository ;)

**Comment by elrond1975** [comment]
ok
ty :)
