### ISSUE TITLE
Missing "clear logs" button in connector

### ISSUE THREAD

**Issue by warlof** [warlof/seat-connector#52]
@Nfinished

Spoke with Warlof a bit ago about clearing connector logs, he suggested that there was a clear button on /seat-connector/logs but we both discovered it must have been removed at some point.

I'm nearing 2,000,000 entries from public users joining our TeamSpeak, would really appreciate a way to wipe them out.

**Comment by Nfinished** [comment]
Thank you!

**Comment by jediefe** [comment]
I strongly encourage this feature. My log contains 6.5m entries. Fewer mass on the DB would be helpful, although the system performs quite well given the circumstances. 
![grafik](https://user-images.githubusercontent.com/1344247/104814969-05821980-5812-11eb-8eef-fe445f52714b.png)
