### ISSUE TITLE
Disregard other sets on server

### ISSUE THREAD

**Issue by matsfinsas** [warlof/seat-connector#6]
It seems to remove all other sets not defined in Access Management.

Say certain sets should only be added/removed manually, but they should also have `corp-set`. How can this be done?

What it should be doing:
- Adds and remove defined sets in Access Management
- Ignore all other sets not defined

**Comment by warlof** [comment]
@Xtrah not feasable and will not change.

Connector is checking granted sets, applicable sets and apply delta if any.
Allowing certain set to be granted out of SeAT is an open door to unmaintained user.
