### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by JacobOkanta** [warlof/seat-connector#8]
I suddenly had my permissions removed by the connector as I had biomassed a character earlier today after this happened I decided to do an update on the connector and SeAT as I was not yet aware that the character was the issue. After updating and deleting the biomassed character from SeAT I can no longer access the Teamspeak connector this happens when I click on it https://pastebin.com/iC8csXYa I seem to recall having a somewhat similar issue with the Discord connector but am not certain how to correct it with the Teamspeak version.

**Comment by warlof** [comment]
Hi @JacobOkanta, you need to run migrations using `php artisan migrate`

**Comment by JacobOkanta** [comment]
It is now working properly. Thanks!
