### ISSUE TITLE
Discord connector

### ISSUE THREAD

**Issue by sgeine** [warlof/seat-connector#9]
the callback url is now broken from the old discord url. can the new location be added to the documentation and updated in this ticket?

**Comment by warlof** [comment]
@sgeine discord haven't be switcher to connector yet
Documentation will be updated when it will be done

Regarding the callback, it should be
`/seat-connector/registration/discord/callback`
`/seat-connector/settings/discord/callback`

**Comment by sgeine** [comment]
thank you, that's weird, both my teamspeak and discord broke with the major rev update. what directory is seat-connector in? I have everything in /var/www/seat. also the discord connector shows up in the new connector interface but I appear to have no way of creating "set" roles.

**Comment by warlof** [comment]
If you're on a production environment, I recommand to switch to stable version which is still `3.*` for discord. There are no major update for discord actually. 

Teamspeak has been released with `4.*` and is compatible with this package. Previous version are deprecated.

If you're coming from a version prior to 4.x, you can use an upgrade command which will convert data structure into new one. `php artisan seat-connector:convert:teamspeak`
Ref: https://github.com/warlof/seat-teamspeak/blob/master/CHANGELOG.md#400

**Comment by sgeine** [comment]
@warlof I'll roll back to the old discord. btw thanks for your hard work and great features.
